### ISSUE TITLE
Cannot find documentation - Vuejs and Dart

### ISSUE THREAD

**Issue by EricEon** [toiletbril/dedoc#11]
Just asking here because i can't seem to find the Dart Programming Language and Vuejs Documentation. I need some help.
Thank you.

**Comment by toiletbril** [comment]
Dart and Vue only have version-specific packages available, so they won't show up in `dedoc ls` without specifying `--all`.

```sh
$ dedoc ls --all --search=dart
dart~2, dart~1
$ dedoc ls --all --search=vue
vue~3, vue~2, vue~1, vue_router~4, vue_router~3, vueuse, vuex~4, vuex~3
```

**Comment by EricEon** [comment]
Thanks a lot for answering the question.
